language: node_js
node_js: stable

cache:
  directories:
    - node_modules

branches:
  only:
    - blog-source

before_install:
  - npm install -g hexo-cli
  

# S: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-sftp --save


# before_script:
 # - npm install -g gulp
    
script:
  - hexo clean
  - hexo generate
  - hexo deploy

# after_script:
#   - git config user.name "coymaple"
#   - git config user.email "dxd0403@163.com"
#   - sed -i "s/myblog/${myblog}/g" ./_config.yml
#   - hexo deploy